sudo: required
os: osx
osx_image: xcode9.3beta

before_install:
  - brew update
  - brew install python
    
matrix:
  include:
    - language: python
      python: 2.7
      script:
        - python --version
        - python ($TRAVIS_BUILD_DIR)/setup.py

