sudo: required

script: 
      ./setup_deps.sh
      xcodebuild clean build -workspace ./engine/builds/xcode/wolf.engine.vulkan.metal.macOS.xcworkspace -scheme wolf.system.macOS -sdk macosx10.13 -configuration Debug

matrix:
  include:
    - os: osx
      osx_image: xcode9.3beta
      language: cpp
      compiler: clang
      xcode_workspace: ./engine/builds/xcode/wolf.engine.vulkan.metal.macOS.xworkspace
      xcode_scheme: wolf.system.macOS


