sudo: required

matrix:
  include:
    - os: osx
      osx_image: xcode9.3beta
      language: cpp
      compiler: clang
        
before_install:
  - sudo chmod +x ($TRAVIS_BUILD_DIR)/setup_deps.sh
  - ($TRAVIS_BUILD_DIR)/setup_deps.sh


