sudo: required

script: 
      ./build.sh

matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      language: cpp
      compiler: clang
      xcode_workspace: ./engine/builds/xcode/wolf.engine.vulkan.metal.macOS.xworkspace
      xcode_scheme: wolf.system.macOS


