sudo: required

script: ./setup_deps.sh

matrix:
  include:
    - os: osx
      osx_image: xcode9.3beta
      language: cpp
      compiler: clang
      xcode_project: ./engine/builds/xcode/wolf.engine.vulkan.metal.macOS.xworkspace
      xcode_scheme: wolf_vulkan_metal_macOS


