sudo: required

before_install:
  - chmod +x install.sh

script: 
      ./install.sh

matrix:
  include:
    - os: osx
      osx_image: xcode9.3beta
      language: cpp
      compiler: clang
      xcode_workspace: ./engine/builds/xcode/wolf.engine.vulkan.metal.macOS.xworkspace
      xcode_scheme: wolf_vulkan_metal_macOS


