version: 1.0.{build}
image: Visual Studio 2017
platform: x64
configuration: Debug

matrix:
    fast_finish: true
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.14"
      PYTHON_ARCH: "64"
	  
    exclude:
    - platform: x86
      configuration: Debug
    - platform: x86
      configuration: Release
    - platform: x64
      configuration: Release
	  
install:
    # python requirements needed to ubpack deps
    - "%PYTHON%\\python.exe c:\\projects\\wolf-engine\\setup.py"
init:
    - "%PYTHON%\\python.exe --version"
build:
  project: c:\\projects\\wolf-engine\\engine\\builds\\mvsc\\wolf.engine.vulkan.Win32.sln
  verbosity: minimal
skip_commits:
  files:
    - content/*
    - docs/*
    - samples/*
    - utilities/*
    - .gitattributes
    - .gitignore
    - Logo.jpg
    - /**/*.md

