version: 1.0.{build}

image: Visual Studio 2017
platform: x64
configuration: Debug

environment:
  matrix:  
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x" # currently 2.7.9
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_ARCH% %MSVC_VERSION%"
  - "%PYTHON%\\python.exe --version"
 
install:
  # python requirements needed to ubpack deps
  - "%PYTHON%\\python.exe c:\\projects\\Wolf.Engine\\setup.py"

build:
  project: wolf.engine.vulkan.Win32.sln

