version: 2
jobs:
  build:
    docker:
      - image: ubuntu:bionic
        dependencies:
          pre:
            - sudo apt-get update; sudo apt-get install clang
    steps:
      - checkout
      - run:
          name: Greeting
          command: clang --version
